"""init: defined inital User, Catalog, and Action tables

Revision ID: de02277e08c4
Revises: 
Create Date: 2025-11-22 18:11:36.785705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de02277e08c4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=32), nullable=False),
    sa.Column('last_name', sa.String(length=32), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('role', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('action_type', sa.String(length=50), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('target_type', sa.String(length=50), nullable=True),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('details', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('actions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_actions_action_type'), ['action_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_actions_timestamp'), ['timestamp'], unique=False)

    op.create_table('catalog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('img_name', sa.String(length=128), nullable=True),
    sa.Column('category', sa.Enum('Bra', 'Hat', 'Outerwear', 'Pants', 'Shirt', 'Shoes', 'Shorts', 'Socks', 'Underwear', name='category_enum'), nullable=False),
    sa.Column('color', sa.Enum('Black', 'White', 'Gray', 'Brown', 'Tan', 'Red', 'Orange', 'Yellow', 'Green', 'Blue', 'Purple', 'Pink', name='color_enum'), nullable=False),
    sa.Column('size', sa.String(length=4), nullable=False),
    sa.Column('times_worn', sa.Integer(), nullable=True),
    sa.Column('last_worn', sa.DateTime(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('catalog', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_catalog_img_name'), ['img_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_catalog_last_worn'), ['last_worn'], unique=False)
        batch_op.create_index(batch_op.f('ix_catalog_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_catalog_priority'), ['priority'], unique=False)
        batch_op.create_index(batch_op.f('ix_catalog_size'), ['size'], unique=False)
        batch_op.create_index(batch_op.f('ix_catalog_times_worn'), ['times_worn'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('catalog', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_catalog_times_worn'))
        batch_op.drop_index(batch_op.f('ix_catalog_size'))
        batch_op.drop_index(batch_op.f('ix_catalog_priority'))
        batch_op.drop_index(batch_op.f('ix_catalog_name'))
        batch_op.drop_index(batch_op.f('ix_catalog_last_worn'))
        batch_op.drop_index(batch_op.f('ix_catalog_img_name'))

    op.drop_table('catalog')
    with op.batch_alter_table('actions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_actions_timestamp'))
        batch_op.drop_index(batch_op.f('ix_actions_action_type'))

    op.drop_table('actions')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_role'))

    op.drop_table('users')
    # ### end Alembic commands ###
